const Options = [
    {name: 'Achates', value: 'Achates'}, 
    {name: 'Adlay', value: 'Adlay'},
    {name: 'Adventurer Ras', value: 'Adventurer Ras'},
    {name: 'Ainos', value: 'Ainos'},
    {name: 'Ains', value: 'Ains'},
    {name: 'Aither', value: 'Aither'},
    {name: 'Alencia', value: 'Alencia'},
    {name: 'Alexa', value: 'Alexa'},
    {name: 'All-Rounder Wanda', value: 'All-Rounder Wanda'},
    {name: 'Ambitious Tywin', value: 'Ambitious Tywin'},
    {name: 'Angelic Montmorancy', value: 'Angelic Montmorancy'},
    {name: 'Angelica', value: 'Angelica'},
    {name: 'Apocalypse Ravi', value: 'Apocalypse Ravi'},
    {name: 'Aramintha', value: 'Aramintha'},
    {name: 'Arbiter Vildred', value: 'Arbiter Vildred'},
    {name: 'Armin', value: 'Armin'},
    {name: 'Arowell', value: 'Arowell'},
    {name: 'Assassin Cartuja', value: 'Assassin Cartuja'},
    {name: 'Assassin Cidd', value: 'Assassin Cidd'},
    {name: 'Assassin Coli', value: 'Assassin Coli'},
    {name: 'Auxiliary Lots', value: 'Auxiliary Lots'},
    {name: 'Azalea', value: 'Azalea'},
    {name: 'Baal and Sezan', value: 'Baal and Sezan'},
    {name: 'Baiken', value: 'Baiken'},
    {name: 'Basar', value: 'Basar'},
    {name: 'Bask', value: 'Bask'},
    {name: 'Batisse', value: 'Batisse'},
    {name: 'Bellona', value: 'Bellona'},
    {name: 'Benevolent Romann', value: 'Benevolent Romann'},
    {name: 'Blaze Dingo', value: 'Blaze Dingo'},
    {name: 'Blood Blade Karin', value: 'Blood Blade Karin'},
    {name: 'Blood Moon Haste', value: 'Blood Moon Haste'},
    {name: 'Briar Witch Iseria', value: 'Briar Witch Iseria'},
    {name: 'Butcher Corps Inquisitor', value: 'Butcher Corps Inquisitor'},
    {name: 'Captain Rikoris', value: 'Captain Rikoris'},
    {name: 'Carmainerose', value: 'Carmainerose'},
    {name: 'Carrot', value: 'Carrot'},
    {name: 'Cartuja', value: 'Cartuja'},
    {name: 'Cecilia', value: 'Cecilia'},
    {name: 'Celeste', value: 'Celeste'},
    {name: 'Celestial Mercedes', value: 'Celestial Mercedes'},
    {name: 'Celine', value: 'Celine'},
    {name: 'Cerise', value: 'Cerise'},
    {name: 'Cermia', value: 'Cermia'},
    {name: 'Challenger Dominiel', value: 'Challenger Dominiel'},
    {name: 'Champion Zerato', value: 'Champion Zerato'},
    {name: 'Chaos Inquisitor', value: 'Chaos Inquisitor'},
    {name: 'Chaos Sect Axe', value: 'Chaos Sect Axe'},
    {name: 'Charles', value: 'Charles'},
    {name: 'Charlotte', value: 'Charlotte'},
    {name: 'Chloe', value: 'Chloe'},
    {name: 'Choux', value: 'Choux'},
    {name: 'Church of Ilryos Axe', value: 'Church of Ilryos Axe'},
    {name: 'Cidd', value: 'Cidd'},
    {name: 'Clarissa', value: 'Clarissa'},
    {name: 'Coli', value: 'Coli'},
    {name: 'Commander Lorina', value: 'Commander Lorina'},
    {name: 'Corvus', value: 'Corvus'},
    {name: 'Crescent Moon Rin', value: 'Crescent Moon Rin'},
    {name: 'Crimson Armin', value: 'Crimson Armin'},
    {name: 'Crozet', value: 'Crozet'},
    {name: 'Dark Corvus', value: 'Dark Corvus'},
    {name: 'Desert Jewel Basar', value: 'Desert Jewel Basar'},
    {name: 'Destina', value: 'Destina'},
    {name: 'Diene', value: 'Diene'},
    {name: 'Dingo', value: 'Dingo'},
    {name: 'Dizzy', value: 'Dizzy'},
    {name: 'Dominiel', value: 'Dominiel'},
    {name: 'Doris', value: 'Doris'},
    {name: 'Eaton', value: 'Eaton'},
    {name: 'Elena', value: 'Elena'},
    {name: 'Elphelt Valentine', value: 'Elphelt Valentine'},
    {name: 'Elson', value: 'Elson'},
    {name: 'Enott', value: 'Enott'},
    {name: 'Ervalen', value: 'Ervalen'},
    {name: 'Faithless Lidica', value: 'Faithless Lidica'},
    {name: 'Falconer Kluri', value: 'Falconer Kluri'},
    {name: 'Fallen Cecilia', value: 'Fallen Cecilia'},
    {name: 'Fighter Maya', value: 'Fighter Maya'},
    {name: 'Flan', value: 'Flan'},
    {name: 'Free Spirit Tieria', value: 'Free Spirit Tieria'},
    {name: 'Furious', value: 'Furious'},
    {name: 'General Purrgis', value: 'General Purrgis'},
    {name: 'Glenn', value: 'Glenn'},
    {name: 'Gloomyrain', value: 'Gloomyrain'},
    {name: 'Godmother', value: 'Godmother'},
    {name: 'Guider Aither', value: 'Guider Aither'},
    {name: 'Gunther', value: 'Gunther'},
    {name: 'Haste', value: 'Haste'},
    {name: 'Hataan', value: 'Hataan'},
    {name: 'Hazel', value: 'Hazel'},
    {name: 'Helga', value: 'Helga'},
    {name: 'Holiday Yufine', value: 'Holiday Yufine'},
    {name: 'Hurado', value: 'Hurado'},
    {name: 'Ian', value: 'Ian'},
    {name: 'Iseria', value: 'Iseria'},
    {name: 'Jecht', value: 'Jecht'},
    {name: 'Jena', value: 'Jena'},
    {name: 'Judge Kise', value: 'Judge Kise'},
    {name: 'Judith', value: 'Judith'},
    {name: 'Karin', value: 'Karin'},
    {name: 'Kawerik', value: 'Kawerik'},
    {name: 'Kayron', value: 'Kayron'},
    {name: 'Ken', value: 'Ken'},
    {name: 'Khawana', value: 'Khawana'},
    {name: 'Khawazu', value: 'Khawazu'},
    {name: 'Kikirat V2', value: 'Kikirat V2'},
    {name: 'Kiris', value: 'Kiris'},
    {name: 'Kise', value: 'Kise'},
    {name: 'Kitty Clarissa', value: 'Kitty Clarissa'},
    {name: 'Kizuna AI', value: 'Kizuna AI'},
    {name: 'Kluri', value: 'Kluri'},
    {name: 'Krau', value: 'Krau'},
    {name: 'Landy', value: 'Landy'},
    {name: 'Last Rider Krau', value: 'Last Rider Krau'},
    {name: 'Lena', value: 'Lena'},
    {name: 'Leo', value: 'Leo'},
    {name: 'Lidica', value: 'Lidica'},
    {name: 'Lilias', value: 'Lilias'},
    {name: 'Lilibet', value: 'Lilibet'},
    {name: 'Little Queen Charlotte', value: 'Little Queen Charlotte'},
    {name: 'Lorina', value: 'Lorina'},
    {name: 'Lots', value: 'Lots'},
    {name: 'Ludwig', value: 'Ludwig'},
    {name: 'Luluca', value: 'Luluca'},
    {name: 'Luna', value: 'Luna'},
    {name: 'Magic Scholar Doris', value: 'Magic Scholar Doris'},
    {name: 'Maid Chloe', value: 'Maid Chloe'},
    {name: 'Martial Artist Ken', value: 'Martial Artist Ken'},
    {name: 'Mascot Hazel', value: 'Mascot Hazel'},
    {name: 'Maya', value: 'Maya'},
    {name: 'Melissa', value: 'Melissa'},
    {name: 'Mercedes', value: 'Mercedes'},
    {name: 'Mercenary Helga', value: 'Mercenary Helga'},
    {name: 'Mirsa', value: 'Mirsa'},
    {name: 'Mistychain', value: 'Mistychain'},
    {name: 'Montmorancy', value: 'Montmorancy'},
    {name: 'Mort', value: 'Mort'},
    {name: 'Mucacha', value: 'Mucacha'},
    {name: 'Mui', value: 'Mui'},
    {name: 'Nemunas', value: 'Nemunas'},
    {name: 'Operator Sigret', value: 'Operator Sigret'},
    {name: 'Otillie', value: 'Otillie'},
    {name: 'Pavel', value: 'Pavel'},
    {name: 'Pearlhorizon', value: 'Pearlhorizon'},
    {name: 'Purrgis', value: 'Purrgis'},
    {name: 'Pyllis', value: 'Pyllis'},
    {name: 'Ras', value: 'Ras'},
    {name: 'Ravi', value: 'Ravi'},
    {name: 'Ray', value: 'Ray'},
    {name: 'Remnant Violet', value: 'Remnant Violet'},
    {name: 'Requiemroar', value: 'Requiemroar'},
    {name: 'Researcher Carrot', value: 'Researcher Carrot'},
    {name: 'Righteous Thief Roozid', value: 'Righteous Thief Roozid'},
    {name: 'Rikoris', value: 'Rikoris'},
    {name: 'Rima', value: 'Rima'},
    {name: 'Rin', value: 'Rin'},
    {name: 'Roaming Warrior Leo', value: 'Roaming Warrior Leo'},
    {name: 'Roana', value: 'Roana'},
    {name: 'Romann', value: 'Romann'},
    {name: 'Roozid', value: 'Roozid'},
    {name: 'Rose', value: 'Rose'},
    {name: 'Ruele of Light', value: 'Ruele of Light'},
    {name: 'Sage Baal and Sezan', value: 'Sage Baal and Sezan'},
    {name: 'Schuri', value: 'Schuri'},
    {name: 'Seaside Bellona', value: 'Seaside Bellona'},
    {name: 'Serila', value: 'Serila'},
    {name: 'Sez', value: 'Sez'},
    {name: 'Shadow Rose', value: 'Shadow Rose'},
    {name: 'Shooting Star Achates', value: 'Shooting Star Achates'},
    {name: 'Sigret', value: 'Sigret'},
    {name: 'Silk', value: 'Silk'},
    {name: 'Silver Blade Aramintha', value: 'Silver Blade Aramintha'},
    {name: 'Sinful Angelica', value: 'Sinful Angelica'},
    {name: 'Sol Badguy', value: 'Sol Badguy'},
    {name: 'Sonia', value: 'Sonia'},
    {name: 'Specimen Sez', value: 'Specimen Sez'},
    {name: 'Specter Tenebria', value: 'Specter Tenebria'},
    {name: 'Surin', value: 'Surin'},
    {name: 'Sven', value: 'Sven'},
    {name: 'Tamarinne', value: 'Tamarinne'},
    {name: 'Taranor Guard', value: 'Taranor Guard'},
    {name: 'Taranor Royal Guard', value: 'Taranor Royal Guard'},
    {name: 'Tempest Surin', value: 'Tempest Surin'},
    {name: 'Tenebria', value: 'Tenebria'},
    {name: 'Tieria', value: 'Tieria'},
    {name: 'Top Model Luluca', value: 'Top Model Luluca'},
    {name: 'Troublemaker Crozet', value: 'Troublemaker Crozet'},
    {name: 'Tywin', value: 'Tywin'},
    {name: 'Vildred', value: 'Vildred'},
    {name: 'Violet', value: 'Violet'},
    {name: 'Vivian', value: 'Vivian'},
    {name: 'Wanda', value: 'Wanda'},
    {name: 'Wanderer Silk', value: 'Wanderer Silk'},
    {name: 'Watcher Schuri', value: 'Watcher Schuri'},
    {name: 'Yufine', value: 'Yufine'},
    {name: 'Yuna', value: 'Yuna'},
    {name: 'Zeno', value: 'Zeno'},
    {name: 'Zerato', value: 'Zerato'},
];

export default Options;